export interface Product {
  id: string
  name: string
  category: string
  description: string
  image: string
  color: string
  packSize: string
  dimensions: string
  gsm: string
  fullDescription: string
}

export const productsData: Product[] = [
  // Paper Plates (Existing)
  {
    id: 'premium-paper-plates',
    name: 'Premium Paper Plates',
    category: 'Paper Plates',
    description: '10" Round Plates',
    image: '/paper-plates-premium-black-and-white.jpg',
    color: 'White',
    packSize: '50 pieces',
    dimensions: '10" diameter x 0.5" depth',
    gsm: '300 GSM',
    fullDescription: 'Premium paper plates perfect for any occasion.',
  },
  {
    id: 'elegant-paper-plates',
    name: 'Elegant Paper Plates',
    category: 'Paper Plates',
    description: '9" Dessert Plates',
    image: '/elegant-paper-plates-black-and-white.jpg',
    color: 'White',
    packSize: '75 pieces',
    dimensions: '9" diameter x 0.4" depth',
    gsm: '280 GSM',
    fullDescription: 'Elegant dessert plates for special events.',
  },

  // Cake Boxes (Mapped: CAKE_BOXES*, BAKERY_BOXES*)
  {
    id: 'cake-box-1',
    name: 'Classic Cake Box',
    category: 'Cake Boxes',
    description: 'Standard Cake Box',
    image: '/images/CAKE_BOXES_img2.jpeg',
    color: 'White',
    packSize: '10 pieces',
    dimensions: '10x10x5',
    gsm: '350 GSM',
    fullDescription: 'Sturdy cake box for safe transport.',
  },
  {
    id: 'cake-box-2',
    name: 'Large Cake Box',
    category: 'Cake Boxes',
    description: 'Large Cake Box',
    image: '/images/CAKE_BOXES_img3.jpeg',
    color: 'White',
    packSize: '10 pieces',
    dimensions: '12x12x6',
    gsm: '350 GSM',
    fullDescription: 'Large cake box for tiered cakes.',
  },
  {
    id: 'bakery-box-1',
    name: 'Bakery Box Small',
    category: 'Cake Boxes',
    description: 'Small Bakery Box',
    image: '/images/BAKERY_BOXES_img1.jpeg',
    color: 'Kraft',
    packSize: '25 pieces',
    dimensions: '8x8x4',
    gsm: '300 GSM',
    fullDescription: 'Perfect for pastries and small cakes.',
  },
  {
    id: 'bakery-box-2',
    name: 'Bakery Box Medium',
    category: 'Cake Boxes',
    description: 'Medium Bakery Box',
    image: '/images/BAKERY_BOXES_img2.jpeg',
    color: 'Kraft',
    packSize: '20 pieces',
    dimensions: '10x10x4',
    gsm: '300 GSM',
    fullDescription: 'Versatile bakery box for various treats.',
  },

  // Gift Wrapping Paper (Mapped: 8SHEET_SOLID*)
  {
    id: 'wrapping-paper-1',
    name: 'Solid Red Wrap',
    category: 'Gift Wrapping Paper',
    description: 'Solid Color Wrap',
    image: '/images/8SHEET_SOLID_img1.jpeg',
    color: 'Red',
    packSize: '8 sheets',
    dimensions: '20x30',
    gsm: '80 GSM',
    fullDescription: 'Vibrant solid color wrapping paper.',
  },
  {
    id: 'wrapping-paper-2',
    name: 'Solid Blue Wrap',
    category: 'Gift Wrapping Paper',
    description: 'Solid Color Wrap',
    image: '/images/8SHEET_SOLID_img2.jpeg',
    color: 'Blue',
    packSize: '8 sheets',
    dimensions: '20x30',
    gsm: '80 GSM',
    fullDescription: 'Classic blue wrapping paper.',
  },
  {
    id: 'wrapping-paper-3',
    name: 'Solid Green Wrap',
    category: 'Gift Wrapping Paper',
    description: 'Solid Color Wrap',
    image: '/images/8SHEET_SOLID_img3.jpeg',
    color: 'Green',
    packSize: '8 sheets',
    dimensions: '20x30',
    gsm: '80 GSM',
    fullDescription: 'Festive green wrapping paper.',
  },
  {
    id: 'wrapping-paper-4',
    name: 'Solid Yellow Wrap',
    category: 'Gift Wrapping Paper',
    description: 'Solid Color Wrap',
    image: '/images/8SHEET_SOLID_img4.jpeg',
    color: 'Yellow',
    packSize: '8 sheets',
    dimensions: '20x30',
    gsm: '80 GSM',
    fullDescription: 'Bright yellow wrapping paper.',
  },
  {
    id: 'wrapping-paper-5',
    name: 'Solid Purple Wrap',
    category: 'Gift Wrapping Paper',
    description: 'Solid Color Wrap',
    image: '/images/8SHEET_SOLID_img5.jpeg',
    color: 'Purple',
    packSize: '8 sheets',
    dimensions: '20x30',
    gsm: '80 GSM',
    fullDescription: 'Elegant purple wrapping paper.',
  },
  {
    id: 'wrapping-paper-6',
    name: 'Solid Orange Wrap',
    category: 'Gift Wrapping Paper',
    description: 'Solid Color Wrap',
    image: '/images/8SHEET_SOLID_img6.jpeg',
    color: 'Orange',
    packSize: '8 sheets',
    dimensions: '20x30',
    gsm: '80 GSM',
    fullDescription: 'Fun orange wrapping paper.',
  },

  // Streamers (Mapped: 1-PK_STREAMERS*, 2-PK_STREAMERS*)
  {
    id: 'streamer-1',
    name: 'Party Streamer Blue',
    category: 'Streamers',
    description: 'Crepe Paper Streamer',
    image: '/images/1-PK_STREAMERS_img2.jpeg',
    color: 'Blue',
    packSize: '1 roll',
    dimensions: '1.75" x 81\'',
    gsm: 'N/A',
    fullDescription: 'Classic crepe paper streamer for party decoration.',
  },
  {
    id: 'streamer-2',
    name: 'Party Streamer Red',
    category: 'Streamers',
    description: 'Crepe Paper Streamer',
    image: '/images/1-PK_STREAMERS_img4.jpeg',
    color: 'Red',
    packSize: '1 roll',
    dimensions: '1.75" x 81\'',
    gsm: 'N/A',
    fullDescription: 'Vibrant red streamer for celebrations.',
  },
  {
    id: 'streamer-3',
    name: 'Party Streamer Green',
    category: 'Streamers',
    description: 'Crepe Paper Streamer',
    image: '/images/1-PK_STREAMERS_img5.jpeg',
    color: 'Green',
    packSize: '1 roll',
    dimensions: '1.75" x 81\'',
    gsm: 'N/A',
    fullDescription: 'Festive green streamer.',
  },
  {
    id: 'streamer-4',
    name: 'Party Streamer Yellow',
    category: 'Streamers',
    description: 'Crepe Paper Streamer',
    image: '/images/1-PK_STREAMERS_img6.jpeg',
    color: 'Yellow',
    packSize: '1 roll',
    dimensions: '1.75" x 81\'',
    gsm: 'N/A',
    fullDescription: 'Bright yellow streamer.',
  },
  {
    id: 'streamer-5',
    name: 'Double Streamer Pack 1',
    category: 'Streamers',
    description: '2-Pack Streamers',
    image: '/images/2-PK_STREAMERS_img1.jpeg',
    color: 'Assorted',
    packSize: '2 rolls',
    dimensions: '1.75" x 81\' each',
    gsm: 'N/A',
    fullDescription: 'Value pack of streamers.',
  },
  {
    id: 'streamer-6',
    name: 'Double Streamer Pack 2',
    category: 'Streamers',
    description: '2-Pack Streamers',
    image: '/images/2-PK_STREAMERS_img2.jpeg',
    color: 'Assorted',
    packSize: '2 rolls',
    dimensions: '1.75" x 81\' each',
    gsm: 'N/A',
    fullDescription: 'Value pack of streamers.',
  },

  // Gift Boxes (Mapped: GIFT_BOXES*, Gift_Box*)
  {
    id: 'gift-box-1',
    name: 'Luxury Gift Box 1',
    category: 'Gift Boxes',
    description: 'Premium Gift Box',
    image: '/images/GIFT_BOXES_img1.jpeg',
    color: 'Assorted',
    packSize: '1 piece',
    dimensions: 'Various',
    gsm: 'N/A',
    fullDescription: 'Beautifully designed gift box.',
  },
  {
    id: 'gift-box-2',
    name: 'Luxury Gift Box 2',
    category: 'Gift Boxes',
    description: 'Premium Gift Box',
    image: '/images/GIFT_BOXES_img1_1.jpeg',
    color: 'Assorted',
    packSize: '1 piece',
    dimensions: 'Various',
    gsm: 'N/A',
    fullDescription: 'Elegant gift box for special occasions.',
  },
  {
    id: 'gift-box-3',
    name: 'Luxury Gift Box 3',
    category: 'Gift Boxes',
    description: 'Premium Gift Box',
    image: '/images/GIFT_BOXES_img2.jpeg',
    color: 'Assorted',
    packSize: '1 piece',
    dimensions: 'Various',
    gsm: 'N/A',
    fullDescription: 'Stylish gift box.',
  },
  {
    id: 'gift-box-4',
    name: 'Luxury Gift Box 4',
    category: 'Gift Boxes',
    description: 'Premium Gift Box',
    image: '/images/GIFT_BOXES_img2_1.jpeg',
    color: 'Assorted',
    packSize: '1 piece',
    dimensions: 'Various',
    gsm: 'N/A',
    fullDescription: 'Premium quality gift box.',
  },
  {
    id: 'gift-box-5',
    name: 'Luxury Gift Box 5',
    category: 'Gift Boxes',
    description: 'Premium Gift Box',
    image: '/images/GIFT_BOXES_img2_2.jpeg',
    color: 'Assorted',
    packSize: '1 piece',
    dimensions: 'Various',
    gsm: 'N/A',
    fullDescription: 'Decorative gift box.',
  },
  {
    id: 'gift-box-6',
    name: 'Luxury Gift Box 6',
    category: 'Gift Boxes',
    description: 'Premium Gift Box',
    image: '/images/GIFT_BOXES_img2_3.jpeg',
    color: 'Assorted',
    packSize: '1 piece',
    dimensions: 'Various',
    gsm: 'N/A',
    fullDescription: 'High-end gift presentation.',
  },

  // Gift Tissue Paper (Mapped: KRAFT, LWC, METALLIC, HOLOGRAM, MULTI, POLKA, PRINTED, TISSUE)
  {
    id: 'tissue-kraft-1',
    name: 'Kraft Tissue 1',
    category: 'Gift Tissue Paper',
    description: 'Kraft Tissue',
    image: '/images/KRAFT_GIFT_img1.jpeg',
    color: 'Kraft',
    packSize: '24 sheets',
    dimensions: '20x30',
    gsm: '17 GSM',
    fullDescription: 'Natural kraft tissue paper.',
  },
  {
    id: 'tissue-lwc-1',
    name: 'LWC Tissue 1',
    category: 'Gift Tissue Paper',
    description: 'LWC Tissue',
    image: '/images/LWC_GIFT_img1.jpeg',
    color: 'Assorted',
    packSize: '24 sheets',
    dimensions: '20x30',
    gsm: '17 GSM',
    fullDescription: 'Lightweight coated tissue paper.',
  },
  {
    id: 'tissue-metallic-1',
    name: 'Metallic Tissue 1',
    category: 'Gift Tissue Paper',
    description: 'Metallic Finish',
    image: '/images/METALLIC_GIFT_img1.jpeg',
    color: 'Metallic',
    packSize: '10 sheets',
    dimensions: '20x30',
    gsm: '17 GSM',
    fullDescription: 'Shimmering metallic tissue paper.',
  },
  {
    id: 'tissue-hologram-1',
    name: 'Hologram Tissue 1',
    category: 'Gift Tissue Paper',
    description: 'Holographic Finish',
    image: '/images/HOLOGRAM_GIFT_img1.jpeg',
    color: 'Holographic',
    packSize: '10 sheets',
    dimensions: '20x30',
    gsm: '17 GSM',
    fullDescription: 'Eye-catching holographic tissue.',
  },
  {
    id: 'tissue-polka-1',
    name: 'Polka Dot Tissue 1',
    category: 'Gift Tissue Paper',
    description: 'Polka Dot Pattern',
    image: '/images/POLKA_DOTS_img2.jpeg',
    color: 'Assorted',
    packSize: '20 sheets',
    dimensions: '20x30',
    gsm: '17 GSM',
    fullDescription: 'Fun polka dot tissue paper.',
  },
  {
    id: 'tissue-polka-2',
    name: 'Polka Dot Tissue 2',
    category: 'Gift Tissue Paper',
    description: 'Polka Dot Pattern',
    image: '/images/POLKA_DOTS_img3.jpeg',
    color: 'Assorted',
    packSize: '20 sheets',
    dimensions: '20x30',
    gsm: '17 GSM',
    fullDescription: 'Classic polka dot design.',
  },
  {
    id: 'tissue-printed-1',
    name: 'Printed Tissue 1',
    category: 'Gift Tissue Paper',
    description: 'Printed Design',
    image: '/images/PRINTED_TISSUE_img1.jpeg',
    color: 'Assorted',
    packSize: '20 sheets',
    dimensions: '20x30',
    gsm: '17 GSM',
    fullDescription: 'Beautifully printed tissue paper.',
  },
  {
    id: 'tissue-printed-2',
    name: 'Printed Tissue 2',
    category: 'Gift Tissue Paper',
    description: 'Printed Design',
    image: '/images/PRINTED_TISSUE_img2.jpeg',
    color: 'Assorted',
    packSize: '20 sheets',
    dimensions: '20x30',
    gsm: '17 GSM',
    fullDescription: 'Elegant printed patterns.',
  },

  // Crinkle Cut Paper (Existing)
  {
    id: 'natural-crinkle-paper',
    name: 'Natural Crinkle Paper',
    category: 'Crinkle Cut Paper',
    description: 'Gift Basket Fill',
    image: '/natural-crinkle-paper-black-and-white.jpg',
    color: 'Natural',
    packSize: '2 lbs',
    dimensions: 'Shredded strips',
    gsm: 'N/A',
    fullDescription: 'Natural crinkle cut paper ideal for gift basket filling.',
  },
]

export function getProductById(id: string): Product | undefined {
  return productsData.find(product => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return productsData.filter(product => product.category === category)
}
